version: "3"
services:

    python:
        build: ./python
        ports:
            - "9380:9380"
            - "9360:9360"

        volumes:
            - "/var/lib/fate/log:/fate/logs"
            - "/var/lib/fate/data:/fate/fate_flow"
        command: bash docker-entrypoint.sh
        container_name: fate_python
    fateboard:
        build: ./fateboard
        links:
            - python
        ports:
            - "8080:8080"
        depends_on:
            - python
        volumes:
            - "/var/lib/fate/log:/data/projects/fate/python/logs"
            - "/var/lib/fate/data:/fate/fate_flow"

        command: bash docker-entrypoint.sh
        container_name: fate_fateboard